# Generated by Django 5.1 on 2024-08-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_fm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='FM',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
