# Generated by Django 5.1 on 2024-08-13 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_fm_alter_customer_table_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
